### ISSUE TITLE
Issue building production instance from scratch

### ISSUE THREAD

**Issue by techwebhosting** [historyforge/historyforge#234]
I have been trying unsuccessfully for a few months now to build history forge following the wiki for deployment of a production system. 

No matter what configuration I try, and whether I use a digital ocean droplet or my own Ubuntu 20 deployment I get the following error during the build. I am not sure that this is a bug per say, but I am at a loss where to go from here. Any guidance would be greatly appreciated. 

```
-----> Releasing hf...
-----> Deploying hf...
 !     Predeploy command declared: 'bundle exec rails db:migrate db:seed'
       rails aborted!
       StandardError: An error has occurred, this and all later migrations canceled:
       PG::UndefinedTable: ERROR:  relation "settings" does not exist
       LINE 1: SELECT "settings".* FROM "settings"
                                        ^
       /app/app/models/setting.rb:38:in `each_with_object'
       /app/app/models/setting.rb:38:in `block in load'
       /app/app/models/setting.rb:37:in `load'
       /app/app/models/app_config.rb:6:in `[]'
       /app/app/models/building.rb:163:in `<class:Building>'
       /app/app/models/building.rb:55:in `<main>'
       /app/db/migrate/20230115211545_restore_auto_strip_attributes.rb:3:in `up'
       Caused by:
       ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "settings" does not exist
       LINE 1: SELECT "settings".* FROM "settings"
                                        ^
       /app/app/models/setting.rb:38:in `each_with_object'
       /app/app/models/setting.rb:38:in `block in load'
       /app/app/models/setting.rb:37:in `load'
       /app/app/models/app_config.rb:6:in `[]'
       /app/app/models/building.rb:163:in `<class:Building>'
       /app/app/models/building.rb:55:in `<main>'
       /app/db/migrate/20230115211545_restore_auto_strip_attributes.rb:3:in `up'
       Caused by:
       PG::UndefinedTable: ERROR:  relation "settings" does not exist
       LINE 1: SELECT "settings".* FROM "settings"
                                        ^
       /app/app/models/setting.rb:38:in `each_with_object'
       /app/app/models/setting.rb:38:in `block in load'
       /app/app/models/setting.rb:37:in `load'
       /app/app/models/app_config.rb:6:in `[]'

```

**Comment by dfurber** [comment]
Sorry about the trouble! Let's see if we can figure it out. I wonder if you start with `rails db:schema:load` will that work? If it does, then `rails db:seed`.

**Comment by techwebhosting** [comment]
Thanks for the response, I was able to test and now I am getting the following. 

```
-----> Releasing hf...
-----> Checking for predeploy task
-----> Executing predeploy task from app.json: bundle exec rails db:schema:load db:seed
=====> Start of hf predeploy task (1e49a99f8) output
remote:  !     /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
remote:  !     rails aborted!
remote:  !     failed to execute:
remote:  !     psql --set ON_ERROR_STOP=1 --quiet --no-psqlrc --output /dev/null --file /app/db/structure.sql hf
remote:  !     Please check the output above for any errors and make sure that `psql` is installed in your PATH and has proper permissions.
remote:  !     Tasks: TOP => db:schema:load
remote:  !     (See full trace by running task with --trace)
=====> End of hf predeploy task (1e49a99f8) output
remote:  !     Execution of predeploy task failed: bundle exec rails db:schema:load db:seed
remote:  !     exit status 1

```


PSQL is installed on both servers, although I suspect it might be looking for it inside the docker\build environment. I modified the app.json to test this during a deploy, is there a better way to be doing that?

Thanks!

**Comment by dfurber** [comment]
Sorry for delayed response! And for all the trouble. Basically you just need to load the db/structure.sql file into your postgres database. When setting up new forges, I've been doing it by hand, in Dokku it's something like `dokku postgres:import hf < structure.sql`.

**Comment by dfurber** [comment]
However I am adding `postgresql-client` to the Docker image, which should satisfy the `psql` issue.
